{"_default": {"1": {"paths": [{"path": "food_USDA/deliveries/one/status/API_status_branded_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check branded 1", "passed": true, "elapsed": [0.26079008400120074, "seconds"]}]}, {"path": "food_USDA/deliveries/one/status/API_status_foundational_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check foundational 1", "passed": true, "elapsed": [2.410491431997798, "seconds"]}]}, {"path": "supp_NIH/deliveries/one/status/API_status_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "NIH branded 1", "passed": true, "elapsed": [0.20982628699857742, "seconds"]}]}], "alarms": [], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 3, "alarms": 0}}}, "2": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check branded 1", "passed": true, "elapsed": [0.4802579370007152, "seconds"]}]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check foundational 1", "passed": true, "elapsed": [1.6381116999982623, "seconds"]}]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "NIH branded 1", "passed": true, "elapsed": [2.345655003999127, "seconds"]}]}], "alarms": [], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 3, "alarms": 0}}}, "3": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check branded 1", "passed": true, "elapsed": [0.6342655389998981, "seconds"]}]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check foundational 1", "passed": true, "elapsed": [0.7836469419999048, "seconds"]}]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "NIH branded 1", "passed": true, "elapsed": [2.1102958570008923, "seconds"]}]}], "alarms": [], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 3, "alarms": 0}}}, "4": {"paths": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}], "alarms": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "5": {"paths": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}], "alarms": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (\"/online ellipsis/cyte/ellipsis.json\", \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/online ellipsis/cyte/ellipsis.json'"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "6": {"paths": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 25, in <module>", "    fp = open (ellipsis_path, \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crown_safes/mint/vegan/ellipsis.json'"]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 25, in <module>", "    fp = open (ellipsis_path, \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crown_safes/mint/vegan/ellipsis.json'"]}], "alarms": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 25, in <module>", "    fp = open (ellipsis_path, \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crown_safes/mint/vegan/ellipsis.json'"]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 46, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 25, in <module>", "    fp = open (ellipsis_path, \"r\")", "         ^^^^^^^^^^^^^^^^^^^^^^^^^", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crown_safes/mint/vegan/ellipsis.json'"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "7": {"paths": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check branded 1", "passed": true, "elapsed": [0.5808245680000255, "seconds"]}]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "empty": false, "parsed": true, "stats": {"passes": 0, "alarms": 1}, "checks": [{"check": "check foundational 1", "passed": false, "exception": "AssertionError()", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 68, in start", "    checks [ check ] ()", "  File \"<string>\", line 17, in check_foundational_1", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/__init__.py\", line 42, in presently", "    assertions_foundational.run (data)", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/assertions/foundational.py\", line 12, in run", "    assert (\"packageWeight\" in data)", "            ^^^^^^^^^^^^^^^^^^^^^^^", "AssertionError"]}]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "NIH branded 1", "passed": true, "elapsed": [0.4897497399997519, "seconds"]}]}], "alarms": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "checks": [{"check": "check foundational 1", "passed": false, "exception": "AssertionError()", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 68, in start", "    checks [ check ] ()", "  File \"<string>\", line 17, in check_foundational_1", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/__init__.py\", line 42, in presently", "    assertions_foundational.run (data)", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/assertions/foundational.py\", line 12, in run", "    assert (\"packageWeight\" in data)", "            ^^^^^^^^^^^^^^^^^^^^^^^", "AssertionError"]}]}], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 2, "alarms": 1}}}, "8": {"paths": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check branded 1", "passed": true, "elapsed": [0.2688028909997229, "seconds"]}]}, {"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "empty": false, "parsed": true, "stats": {"passes": 0, "alarms": 1}, "checks": [{"check": "check foundational 1", "passed": false, "exception": "AssertionError()", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 68, in start", "    checks [ check ] ()", "  File \"<string>\", line 17, in check_foundational_1", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/__init__.py\", line 42, in presently", "    assertions_foundational.run (data)", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/assertions/foundational.py\", line 12, in run", "    assert (\"packageWeight\" in data)", "            ^^^^^^^^^^^^^^^^^^^^^^^", "AssertionError"]}]}, {"path": "../vegan/clouds/supp_NIH/deliveries/one/status/API_status_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "NIH branded 1", "passed": true, "elapsed": [0.1764063000009628, "seconds"]}]}], "alarms": [{"path": "../vegan/clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "checks": [{"check": "check foundational 1", "passed": false, "exception": "AssertionError()", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 68, in start", "    checks [ check ] ()", "  File \"<string>\", line 17, in check_foundational_1", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/__init__.py\", line 42, in presently", "    assertions_foundational.run (data)", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/assertions/foundational.py\", line 12, in run", "    assert (\"packageWeight\" in data)", "            ^^^^^^^^^^^^^^^^^^^^^^^", "AssertionError"]}]}], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 2, "alarms": 1}}}, "9": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "check branded 1", "passed": true, "elapsed": [0.343870500999401, "seconds"]}]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "empty": false, "parsed": true, "stats": {"passes": 0, "alarms": 1}, "checks": [{"check": "check foundational 1", "passed": false, "exception": "AssertionError()", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 68, in start", "    checks [ check ] ()", "  File \"<string>\", line 17, in check_foundational_1", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/__init__.py\", line 42, in presently", "    assertions_foundational.run (data)", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/assertions/foundational.py\", line 12, in run", "    assert (\"packageWeight\" in data)", "            ^^^^^^^^^^^^^^^^^^^^^^^", "AssertionError"]}]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "empty": false, "parsed": true, "stats": {"passes": 1, "alarms": 0}, "checks": [{"check": "NIH branded 1", "passed": true, "elapsed": [0.2194085039991478, "seconds"]}]}], "alarms": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "checks": [{"check": "check foundational 1", "passed": false, "exception": "AssertionError()", "exception trace": ["Traceback (most recent call last):", "  File \"/home/veganeco/.local/lib/python3.11/site-packages/homeostasis/processes/scan/process/keg/check.py\", line 68, in start", "    checks [ check ] ()", "  File \"<string>\", line 17, in check_foundational_1", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/__init__.py\", line 42, in presently", "    assertions_foundational.run (data)", "  File \"/run/media/veganeco/water/status600.com/pypi/reptilian_climates/modules_series_4/vegan/structures/modules/vegan/clouds/food_USDA/deliveries/one/assertions/foundational.py\", line 12, in run", "    assert (\"packageWeight\" in data)", "            ^^^^^^^^^^^^^^^^^^^^^^^", "AssertionError"]}]}], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 2, "alarms": 1}}}, "10": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/structures/modules_pip/bracelet/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/structures/modules_pip/bracelet/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/structures/modules_pip/bracelet/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}], "alarms": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/structures/modules_pip/bracelet/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/structures/modules/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/structures/modules_pip/bracelet/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/structures/modules/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/structures/modules_pip/bracelet/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/structures/modules/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "11": {"paths": [], "alarms": [], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "12": {"paths": [], "alarms": [], "stats": {"alarms": 0, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "13": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}], "alarms": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "14": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}], "alarms": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/crowns_safes/mint/vegan/ellipsis.json'"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "15": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/vaccines_vegan/mint/vegan/ellipsis.json'"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}], "alarms": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/offline/vaccines_vegan/mint/vegan/ellipsis.json'"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "16": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/online/vaccines_vegan/mint/vegan/ellipsis.json'"]}], "alarms": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/online/vaccines_vegan/mint/vegan/ellipsis.json'"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}, "17": {"paths": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/online/vaccines_vegan/mint/vegan/ellipsis.json'"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/online/vaccines_vegan/mint/vegan/ellipsis.json'"]}], "alarms": [{"path": "clouds/food_USDA/deliveries/one/status/API_status_branded_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "ImportError(\"cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)\")", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 10, in <module>", "ImportError: cannot import name '_ellipses' from 'vegan' (/vegan/venues/stages/vegan/__init__.py)"]}, {"path": "clouds/food_USDA/deliveries/one/status/API_status_foundational_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 11, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/online/vaccines_vegan/mint/vegan/ellipsis.json'"]}, {"path": "clouds/supp_NIH/deliveries/one/status/API_status_1.py", "parsed": false, "alarm": "An exception occurred while scanning the path.", "exception": "FileNotFoundError(2, 'No such file or directory')", "exception trace": ["Traceback (most recent call last):", "  File \"/vegan/venues/stages_pip/volts/processes/scan/process/keg/check.py\", line 54, in start", "    exec (", "  File \"<string>\", line 14, in <module>", "  File \"/vegan/venues/stages/vegan/_ellipses/__init__.py\", line 23, in <module>", "    fp = open (ellipsis_path, \"r\")", "FileNotFoundError: [Errno 2] No such file or directory: '/online/vaccines_vegan/mint/vegan/ellipsis.json'"]}], "stats": {"alarms": 3, "empty": 0, "checks": {"passes": 0, "alarms": 0}}}}}